config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root "home#index"
  
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if current_user
			redirect_to posts_path
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyAjax</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>


</head>
<body>

<% if current_user %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %> 
  <%= link_to "Login", new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col-md-4 blog-main box text-center" id="post_<%= post.id %>">

            <div class="panel panel-info"><!-- Panel Info -->

                  <div class="panel-heading">
                    <h3 class="panel-title"><%= post.title %></h3>
                    <p><%= post.content %></p>
                  </div>

                  <div class="panel-body"><!-- Panel Body -->
                    <div style="color: #3BB2D6;"><%= time_ago_in_words(post.created_at) %></div>
                    <br>

                    <div class="btn-group" role="group" aria-label="...">
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatepost_<%= post.id %>">
                          Edit
                        </button>
                        <%= link_to 'Destroy', post, method: :delete, class: "btn btn-danger", remote: true %>
                    </div>
                  </div><!-- Panel Body -->

            </div><!-- Panel Info -->


            <!-- Modal - update posts -->
                  <%= form_for(post, :method => :put, remote: true) do |f| %>
                  <div class="modal fade" id="myupdatepost_<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Edit</h4>
                      </div>
                      <div class="modal-body">

                      <div class="field">
                        <%= f.label :title %><br>
                        <%= f.text_area :title, class: "form-control" %>
                      </div>
                      <div class="field">
                        <%= f.label :content %><br>
                        <%= f.text_area :content, class: "form-control" %>
                      </div>

                      </div>
                      <div class="modal-footer">
                        <button type="button" id="myupdatebutton_<%= post.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
                        <%= submit_tag "Update", class: "btn btn-primary" %>
                      </div>
                    </div>
                  </div>
                  </div>
                  <% end %>
            <!-- Modal -->


</div>

app/views/posts/create.js.erb
$("#mynewpost").modal('hide');
$(".post_title").val('');
$(".post_content").val('');

$("#container_posts").prepend('<%= j render @post %>');
$("#post_<%= @post.id %>").hide().fadeIn(1000);

app/views/posts/destroy.js.erb
$("#post_<%= @post.id %>").fadeOut(500, function(){
	$(this).remove();
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">

    <div class="row">
      <div class="text-center">
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#mynewpost">
            New Post
          </button>
      </div>
    </div>

    <br>
    <hr>

    <div class="row" id="container_posts">
        <%= render @posts %>
    </div>


    <!-- Modal  create action -->
      <%= form_for(@post, remote: true) do |f| %>
        <div class="modal fade" id="mynewpost" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">

            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Post</h4>
            </div>
            
            <div class="modal-body">
              <div class="field">
                <%= f.label :title %><br>
                <%= f.text_area :title, class: "form-control post_title" %>
              </div>
              <div class="field">
                <%= f.label :content %><br>
                <%= f.text_area :content, class: "form-control post_content" %>
              </div>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Close</button>
              <%= submit_tag "Create", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
        </div>
      <% end %>
    <!-- Modal -->



</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/update.js.erb
$("#myupdatepost_<%= @post.id %>").modal('hide');

$("#post_<%= @post.id %>").fadeOut(500, function(){

	$(this).remove();
	$("#container_posts").prepend('<%= j render @post %>');
	
});